version: '3.4'
services:
  keycloak:
    build: ./keycloak
    image: olihock/keycloak:1.0.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
    ports:
      - "18092:8080"
    command:
      - start-dev
      - --import-realm
    networks:
      - network
  resource-server:
    build: ./resource-server
    image: olihock/oauth2-resource-server:1.0.0
    container_name: oauth2-resource-server
    ports:
      - "18091:18091"
    environment:
      ISSUER_URI: https://integ.dynv6.net/keycloak/realms/oauth2-framework
    volumes:
      - "${HOME}/.m2:/root/.m2"
    networks:
      - network
networks:
  network: